[package]
name = "xdebug"
version = "0.1.0"
edition = "2021"
description = "PHP xdebug client library"
license = "MIT"
repository = "https://github.com/yakupars/xdebug.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
